### ISSUE TITLE
install issues with wireguard installed

### ISSUE THREAD

**Issue by fl-y** [pointnetwork/pointnetwork#15]
[Environment]
- current latest master (commit 652595d441d4f34f140340058d4f90384001489f)
- node v10.15.3 and npm with nothing global installed
- Wireguard program is running but not turned on

[Steps to reproduce]
- clone the repo to desired directory and enter
- `nvm use v10.15.3`
- `npm i`

installation will fail with a message along the lines of
```
> @deadcanaries/granax@3.2.5 postinstall $DIR/pointNetwork/point-node/node_modules/@deadcanaries/granax
> node script/download-tbb.js

read ECONNRESET
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

[How to fix]
- Turn on WIreguard and run `npm i`

**Comment by jensendarren** [comment]
Issue is fixed and a workaround is outlined in the README [here](https://github.com/pointnetwork/pointnetwork#troubleshooting-installing-tor-browser-during-npm-install). I'll close the issue. Please feel free to reopen if needed.
