### ISSUE TITLE
Reason behind choosing JS and Typescript for whole Point tools

### ISSUE THREAD

**Issue by chandanpasunoori** [pointnetwork/pointnetwork#557]
I'm interested in project goals and efforts, I want to know why creators chose JS ecosystem for developing these tools, while many blockchain based tools choosing Rust for their safety guarantees.

**Comment by sergevar** [comment]
Historical choice, today Rust or Go would've been better. But just like with Bitcoin, Ethereum clients etc. - there doesn't have to exist only one implementation, hopefully in the future there will be many others compatible with each other.

This is an experimental stage that allows us to quickly iterate, as the protocol takes shape under real use cases and ossifies, this code will most likely be thrown out.
